"""

Inserindo relacionamento de `Role` ao
`User`

Revision ID: 377d59298f64
Revises: fd7e788ba77f
Create Date: 2016-03-15 15:21:53.685340

"""

# revision identifiers, used by Alembic.
revision = '377d59298f64'
down_revision = 'fd7e788ba77f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    ### end Alembic commands ###
