"""

Criando os modelos `User` e `Role` e
inserindo dois tipos de papéis como:
    - SuperAdministrador
    - Administrador

Revision ID: fd7e788ba77f
Revises: None
Create Date: 2016-03-15 12:46:35.966265

"""

# revision identifiers, used by Alembic.
revision = 'fd7e788ba77f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    insert_roles()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###


def insert_roles():
    role_table = table('roles',
        column('name', sa.String)
    )
    op.bulk_insert(role_table, [
        {'name': 'superadmin'},
        {'name': 'admin'}
    ])
